name: Laravel and React Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Install Backend Dependencies
        run: |
          docker-compose exec backend composer install
          docker-compose exec backend php artisan key:generate
          docker-compose exec backend php artisan migrate

      - name: Run Laravel Tests
        run: |
          docker-compose exec backend php artisan test

      - name: Verify Frontend
        run: |
          docker-compose exec frontend npm install
          docker-compose exec frontend npm test
          docker-compose exec frontend npm run build
          

      - name: Tear Down Docker Compose
        if: always()
        run: docker-compose down
